# Generated by Django 5.2.13 on 2026-04-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='sourceexcerpt',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='sources.sourcedocument'),
        ),
        migrations.AddField(
            model_name='sourceexcerpt',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_excerpts', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['workspace', 'status'], name='sources_sou_workspa_e8d758_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['workspace', 'source_type'], name='sources_sou_workspa_e96096_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['workspace', 'updated_at'], name='sources_sou_workspa_5003b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceexcerpt',
            index=models.Index(fields=['workspace', 'document'], name='sources_sou_workspa_683557_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceexcerpt',
            index=models.Index(fields=['document', 'order_index'], name='sources_sou_documen_9affaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceexcerpt',
            constraint=models.UniqueConstraint(fields=('document', 'order_index'), name='unique_excerpt_order_per_document'),
        ),
    ]
