# Generated by Django 5.2.13 on 2026-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_rank', models.PositiveIntegerField(default=1)),
                ('rationale', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('relevance_rank', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BriefingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stub', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('answer_text', models.TextField()),
                ('confidence_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('reviewed', 'Reviewed'), ('superseded', 'Superseded')], default='generated', max_length=20)),
                ('generation_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BriefingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('audience', models.CharField(blank=True, default='', max_length=120)),
                ('goal', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('needs_review', 'Needs Review')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
