# Generated by Django 5.2.13 on 2026-04-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefings', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercitation',
            name='excerpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_citations', to='sources.sourceexcerpt'),
        ),
    ]
