# Generated by Django 5.2.13 on 2026-04-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefings', '0002_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='briefinganswer',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_briefing_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answercitation',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='briefings.briefinganswer'),
        ),
        migrations.AddField(
            model_name='briefingrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briefingrequest',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_requests', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='briefinganswer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='briefings.briefingrequest'),
        ),
        migrations.AddConstraint(
            model_name='answercitation',
            constraint=models.UniqueConstraint(fields=('answer', 'excerpt'), name='unique_citation_per_answer_excerpt'),
        ),
        migrations.AddIndex(
            model_name='briefingrequest',
            index=models.Index(fields=['workspace', 'status'], name='briefings_b_workspa_f4c8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='briefingrequest',
            index=models.Index(fields=['workspace', 'updated_at'], name='briefings_b_workspa_bfc967_idx'),
        ),
        migrations.AddIndex(
            model_name='briefinganswer',
            index=models.Index(fields=['request', 'status'], name='briefings_b_request_ea7e24_idx'),
        ),
        migrations.AddIndex(
            model_name='briefinganswer',
            index=models.Index(fields=['request', 'created_at'], name='briefings_b_request_0aceb6_idx'),
        ),
    ]
