# Generated by Django 5.2.13 on 2026-04-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(default='heuristic', max_length=50)),
                ('groundedness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('citation_coverage_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('review', 'Review'), ('fail', 'Fail')], default='review', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='briefings.briefinganswer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='briefings.briefinganswer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
