# Generated by Django 5.2.13 on 2026-04-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdecision',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['answer', 'created_at'], name='evaluations_answer__848e01_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['verdict', 'created_at'], name='evaluations_verdict_b0fcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['answer', 'created_at'], name='evaluations_answer__02c5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['reviewer', 'created_at'], name='evaluations_reviewe_4d15dd_idx'),
        ),
    ]
